In [7]:
import numpy as np
from HUST_PPS import LapBangTichLagrange, TinhCyLagrange, LapBangTinhCyLagrange, LapBangThuongLagrange, DaThucNoiSuyLagrange, Horner, HornerTinhDaoHam
from HUST_PPS import ReadxyFromFile, FormatNumber

1. Đọc File
- Dòng đầu chứa x, mỗi số cách nhau bởi dấu cách
- Dòng sau chứa y, mỗi số cách nhau bởi dấu cách

In [8]:
file_path = '/workspaces/HUST_PPS/files/TimDaThucNoiSuyLagrange.txt' # Thay file_path
x,y = ReadxyFromFile(file_path)
print(x)
print(y)

[1.2 1.4 1.6 1.8 2.  2.2 2.4]
[0.3529 1.4501 2.6476 3.9216 5.2484 6.6055 7.9722]


In [9]:
FormatNumber(4)

In [10]:
LapBangTinhCyLagrange(x,y)

array([[ 1. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2],
       [-0.2,  1. ,  0.2,  0.4,  0.6,  0.8,  1. ],
       [-0.4, -0.2,  1. ,  0.2,  0.4,  0.6,  0.8],
       [-0.6, -0.4, -0.2,  1. ,  0.2,  0.4,  0.6],
       [-0.8, -0.6, -0.4, -0.2,  1. ,  0.2,  0.4],
       [-1. , -0.8, -0.6, -0.4, -0.2,  1. ,  0.2],
       [-1.2, -1. , -0.8, -0.6, -0.4, -0.2,  1. ]])

In [11]:
TinhCyLagrange(x,y)

array([    7.6584,  -188.8151,   861.849 , -1702.0833,  1708.4635,
        -860.0911,   173.0078])

In [12]:
LapBangTichLagrange(x)

array([[   0.    ,    0.    ,    0.    ,    0.    ,    0.    ,    0.    ,
           0.    ,    1.    ],
       [   0.    ,    0.    ,    0.    ,    0.    ,    0.    ,    0.    ,
           1.    ,   -1.2   ],
       [   0.    ,    0.    ,    0.    ,    0.    ,    0.    ,    1.    ,
          -2.6   ,    1.68  ],
       [   0.    ,    0.    ,    0.    ,    0.    ,    1.    ,   -4.2   ,
           5.84  ,   -2.688 ],
       [   0.    ,    0.    ,    0.    ,    1.    ,   -6.    ,   13.4   ,
         -13.2   ,    4.8384],
       [   0.    ,    0.    ,    1.    ,   -8.    ,   25.4   ,  -40.    ,
          31.2384,   -9.6768],
       [   0.    ,    1.    ,  -10.2   ,   43.    ,  -95.88  ,  119.2384,
         -78.4013,   21.289 ],
       [   1.    ,  -12.6   ,   67.48  , -199.08  ,  349.3504, -364.5734,
         209.452 ,  -51.0935]])

In [13]:
LapBangThuongLagrange(x)

array([[   1.    ,  -11.4   ,   53.8   , -134.52  ,  187.9264, -139.0618,
          42.5779,    0.    ],
       [   1.    ,  -11.2   ,   51.8   , -126.56  ,  172.1664, -123.5405,
          36.4954,    0.    ],
       [   1.    ,  -11.    ,   49.88  , -119.272 ,  158.5152, -110.9491,
          31.9334,    0.    ],
       [   1.    ,  -10.8   ,   48.04  , -112.608 ,  146.656 , -100.5926,
          28.3853,    0.    ],
       [   1.    ,  -10.6   ,   46.28  , -106.52  ,  136.3104,  -91.9526,
          25.5468,   -0.    ],
       [   1.    ,  -10.4   ,   44.6   , -100.96  ,  127.2384,  -84.649 ,
          23.2243,    0.    ],
       [   1.    ,  -10.2   ,   43.    ,  -95.88  ,  119.2384,  -78.4013,
          21.289 ,   -0.    ]])

In [14]:
A = DaThucNoiSuyLagrange(x,y)
A

array([-0.0109,  0.1393, -0.6931,  1.2565,  0.9315,  1.0418, -3.2868])

In [15]:
for i in range(0,len(x)):
    t = len(x) - 1
    sum = 0
    for j in range(0,len(A)):
        sum += (A[j]*(x[i]**t))
        t -= 1
    print(sum)

0.3528999993144968
1.4500999992105639
2.647599999091507
3.921599998956559
5.248399998805326
6.605499998637889
7.972199998454883


Tính f(3.95)

In [16]:
Horner(A,3.95)

(array([-0.0109,  0.0965, -0.3121,  0.0237,  1.0249,  5.0903, 16.8198]),
 np.float64(16.819773927186834))

In [17]:
_ , ans = Horner(A,3.95)
ans

np.float64(16.819773927186834)

Tính f'(3.95)

In [18]:
HornerTinhDaoHam(A,3.95)

([array([-0.0109,  0.0965, -0.3121,  0.0237,  1.0249,  5.0903, 16.8198]),
  array([-0.0109,  0.0536, -0.1004, -0.3729, -0.4479,  3.3212]),
  array([-0.0109,  0.0107, -0.058 , -0.6018, -2.8249]),
  array([-0.0109, -0.0321, -0.1848, -1.3318]),
  array([-0.0109, -0.075 , -0.481 ]),
  array([-0.0109, -0.1178]),
  array([-0.0109])],
 [np.float64(16.819773927186834),
  np.float64(3.3211574332268476),
  np.float64(-5.649825167388128),
  np.float64(-7.990917967314215),
  np.float64(-11.543619790561872),
  np.float64(-14.14062499956606),
  np.float64(-7.812499999947704)])

In [19]:
_ , ans = HornerTinhDaoHam(A,3.95)
ans[1]

np.float64(3.3211574332268476)