In [5]:
import numpy as np
from HUST_PPS import TinhTySaiPhan, TinhCyNewton, LapBangTichLagrange, DaThucNoiSuyNewton
from HUST_PPS import ReadxyFromFile, FormatNumber

Đa thức nội suy Newton tiến

In [6]:
file_path = '/workspaces/HUST_PPS/files/TimDaThucNoiSuyNewton.txt' # Thay file_path
x,y = ReadxyFromFile(file_path)
print(x)
print(y)

[1.57 1.59 1.62 1.64 1.67 1.71 1.74]
[2.4625 2.5857 2.772  2.897  3.086  3.3404 3.5328]


In [7]:
FormatNumber(4)

In [8]:
TinhTySaiPhan(x,y)

array([[   1.57  ,    2.4625,    0.    ,    0.    ,    0.    ,    0.    ,
           0.    ,    0.    ],
       [   1.59  ,    2.5857,    6.16  ,    0.    ,    0.    ,    0.    ,
           0.    ,    0.    ],
       [   1.62  ,    2.772 ,    6.21  ,    1.    ,    0.    ,    0.    ,
           0.    ,    0.    ],
       [   1.64  ,    2.897 ,    6.25  ,    0.8   ,   -2.8571,    0.    ,
           0.    ,    0.    ],
       [   1.67  ,    3.086 ,    6.3   ,    1.    ,    2.5   ,   53.5714,
           0.    ,    0.    ],
       [   1.71  ,    3.3404,    6.36  ,    0.8571,   -1.5873,  -34.0608,
        -625.9448,    0.    ],
       [   1.74  ,    3.5328,    6.4133,    0.7619,   -0.9524,    5.291 ,
         262.3457, 5225.2382]])

In [ ]:
TinhCyNewton(x,y)

array([   2.4625,    6.16  ,    1.    ,   -2.8571,   53.5714, -625.9448,
       5225.2382])

In [10]:
x_1 = x[0:len(x)-1]
LapBangTichLagrange(x_1)

array([[  0.    ,   0.    ,   0.    ,   0.    ,   0.    ,   0.    ,
          1.    ],
       [  0.    ,   0.    ,   0.    ,   0.    ,   0.    ,   1.    ,
         -1.57  ],
       [  0.    ,   0.    ,   0.    ,   0.    ,   1.    ,  -3.16  ,
          2.4963],
       [  0.    ,   0.    ,   0.    ,   1.    ,  -4.78  ,   7.6155,
         -4.044 ],
       [  0.    ,   0.    ,   1.    ,  -6.42  ,  15.4547, -16.5334,
          6.6322],
       [  0.    ,   1.    ,  -8.09  ,  26.1761, -42.3428,  34.243 ,
        -11.0757],
       [  1.    ,  -9.8   ,  40.01  , -87.1039, 106.6491, -69.6312,
         18.9395]])

In [11]:
DaThucNoiSuyNewton(x,y)

array([   5225.2382,  -51833.2796,  214179.2472, -471870.2408,
        584613.975 , -386178.5122,  106258.2625])

Đa thức nội suy Newton lùi

In [12]:
x1 = np.flip(x,axis=0)
y1 = np.flip(y,axis=0)
print(x1)
print(y1)

[1.74 1.71 1.67 1.64 1.62 1.59 1.57]
[3.5328 3.3404 3.086  2.897  2.772  2.5857 2.4625]


In [13]:
TinhTySaiPhan(x1,y1)

array([[   1.74  ,    3.5328,    0.    ,    0.    ,    0.    ,    0.    ,
           0.    ,    0.    ],
       [   1.71  ,    3.3404,    6.4133,    0.    ,    0.    ,    0.    ,
           0.    ,    0.    ],
       [   1.67  ,    3.086 ,    6.36  ,    0.7619,    0.    ,    0.    ,
           0.    ,    0.    ],
       [   1.64  ,    2.897 ,    6.3   ,    0.8571,   -0.9524,    0.    ,
           0.    ,    0.    ],
       [   1.62  ,    2.772 ,    6.25  ,    1.    ,   -1.5873,    5.291 ,
           0.    ,    0.    ],
       [   1.59  ,    2.5857,    6.21  ,    0.8   ,    2.5   ,  -34.0608,
         262.3457,    0.    ],
       [   1.57  ,    2.4625,    6.16  ,    1.    ,   -2.8571,   53.5714,
        -625.9448, 5225.2382]])

In [14]:
TinhCyNewton(x1,y1)

array([   3.5328,    6.4133,    0.7619,   -0.9524,    5.291 ,  262.3457,
       5225.2382])

In [15]:
x_1 = x[0:len(x1)-1]
LapBangTichLagrange(x_1)

array([[  0.    ,   0.    ,   0.    ,   0.    ,   0.    ,   0.    ,
          1.    ],
       [  0.    ,   0.    ,   0.    ,   0.    ,   0.    ,   1.    ,
         -1.57  ],
       [  0.    ,   0.    ,   0.    ,   0.    ,   1.    ,  -3.16  ,
          2.4963],
       [  0.    ,   0.    ,   0.    ,   1.    ,  -4.78  ,   7.6155,
         -4.044 ],
       [  0.    ,   0.    ,   1.    ,  -6.42  ,  15.4547, -16.5334,
          6.6322],
       [  0.    ,   1.    ,  -8.09  ,  26.1761, -42.3428,  34.243 ,
        -11.0757],
       [  1.    ,  -9.8   ,  40.01  , -87.1039, 106.6491, -69.6312,
         18.9395]])

In [16]:
A = DaThucNoiSuyNewton(x1,y1)
A

array([   5225.2382,  -51833.2796,  214179.2472, -471870.2408,
        584613.975 , -386178.5122,  106258.2625])

In [17]:
for i in range(0,len(x)):
    t = len(x) - 1
    sum = 0
    for j in range(0,len(A)):
        sum += (A[j]*(x[i]**t))
        t -= 1
    print(sum)

2.4625000002706656
2.5856999998359242
2.772000000361004
2.897000000361004
3.086000000257627
3.3404000000009546
3.5328000006411457
