In [15]:
import numpy as np
from HUST_PPS import TinhBangSaiPhan, TinhBangSaiPhanGaussI, TinhCySaiPhanGaussI, LapBangTichGaussI, DaThucNoiSuyTrungTamGaussI
from HUST_PPS import TinhBangSaiPhanGaussII, TinhCySaiPhanGaussII, LapBangTichGaussII, DaThucNoiSuyTrungTamGaussII
from HUST_PPS import ReadxyFromFile, FormatNumber

In [16]:
file_path = 'D:/Study/2024.1/PPS/HUST_PPS/files/TimDaThucNoiSuyTrungTamGauss.txt' # Thay file_path
x,y = ReadxyFromFile(file_path)
print(x)
print(y)

[5.25  5.375 5.5   5.625 5.75  5.875 6.   ]
[-3.2541 -3.4223 -3.5371 -3.5967 -3.6001 -3.5474 -3.4393]


In [17]:
FormatNumber(6)

In [18]:
if len(x) % 2 != 0 and len(x) > 1:
    print("Số n thỏa mãn") # n = 2k+1
else:
    print("Số n không thỏa mãn")

Số n thỏa mãn


Gauss I

In [19]:
TinhBangSaiPhan(x,y)

array([[ 5.25  , -3.2541,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ],
       [ 5.375 , -3.4223, -0.1682,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ],
       [ 5.5   , -3.5371, -0.1148,  0.0534,  0.    ,  0.    ,  0.    ,
         0.    ],
       [ 5.625 , -3.5967, -0.0596,  0.0552,  0.0018,  0.    ,  0.    ,
         0.    ],
       [ 5.75  , -3.6001, -0.0034,  0.0562,  0.001 , -0.0008,  0.    ,
         0.    ],
       [ 5.875 , -3.5474,  0.0527,  0.0561, -0.0001, -0.0011, -0.0003,
         0.    ],
       [ 6.    , -3.4393,  0.1081,  0.0554, -0.0007, -0.0006,  0.0005,
         0.0008]])

In [20]:
TinhBangSaiPhanGaussI(x,y,len(x))

array([-3.5967, -0.0034,  0.0562, -0.0001, -0.0011,  0.0005,  0.0008])

In [21]:
TinhCySaiPhanGaussI(x,y,len(x))

array([-3.5967  , -0.0034  ,  0.0281  , -0.000017, -0.000046,  0.000004,
        0.000001])

In [22]:
LapBangTichGaussI(len(x))

array([[  0.,   0.,   0.,   0.,   0.,   0.,   1.],
       [  0.,   0.,   0.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   0.,   0.,   1.,  -1.,   0.],
       [  0.,   0.,   0.,   1.,   0.,  -1.,   0.],
       [  0.,   0.,   1.,  -2.,  -1.,   2.,   0.],
       [  0.,   1.,   0.,  -5.,   0.,   4.,   0.],
       [  1.,  -3.,  -5.,  15.,   4., -12.,   0.]])

In [23]:
DaThucNoiSuyTrungTamGaussI(x,y,len(x))

array([ 0.000001,  0.000001, -0.000051,  0.000071,  0.02815 , -0.031572,
       -3.5967  ])

Gauss II

In [24]:
TinhBangSaiPhan(x,y)

array([[ 5.25  , -3.2541,  0.    ,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ],
       [ 5.375 , -3.4223, -0.1682,  0.    ,  0.    ,  0.    ,  0.    ,
         0.    ],
       [ 5.5   , -3.5371, -0.1148,  0.0534,  0.    ,  0.    ,  0.    ,
         0.    ],
       [ 5.625 , -3.5967, -0.0596,  0.0552,  0.0018,  0.    ,  0.    ,
         0.    ],
       [ 5.75  , -3.6001, -0.0034,  0.0562,  0.001 , -0.0008,  0.    ,
         0.    ],
       [ 5.875 , -3.5474,  0.0527,  0.0561, -0.0001, -0.0011, -0.0003,
         0.    ],
       [ 6.    , -3.4393,  0.1081,  0.0554, -0.0007, -0.0006,  0.0005,
         0.0008]])

In [25]:
TinhBangSaiPhanGaussII(x,y,len(x))

array([-3.5967, -0.0596,  0.0562,  0.001 , -0.0011, -0.0003,  0.0008])

In [26]:
TinhCySaiPhanGaussII(x,y,len(x))

array([-3.5967  , -0.0596  ,  0.0281  ,  0.000167, -0.000046, -0.000002,
        0.000001])

In [27]:
LapBangTichGaussII(len(x))

array([[  0.,   0.,   0.,   0.,   0.,   0.,   1.],
       [  0.,   0.,   0.,   0.,   0.,   1.,   0.],
       [  0.,   0.,   0.,   0.,   1.,   1.,   0.],
       [  0.,   0.,   0.,   1.,   0.,  -1.,   0.],
       [  0.,   0.,   1.,   2.,  -1.,  -2.,   0.],
       [  0.,   1.,   0.,  -5.,   0.,   4.,   0.],
       [  1.,   3.,  -5., -15.,   4.,  12.,   0.]])

In [28]:
DaThucNoiSuyTrungTamGaussII(x,y,len(x))

array([ 0.000001,  0.000001, -0.000051,  0.000071,  0.02815 , -0.031572,
       -3.5967  ])