In [2]:
import numpy as np
from HUST_PPS import LapBangTichLagrange, TinhCyLagrange, LapBangTinhCyLagrange, LapBangThuongLagrange, DaThucNoiSuyLagrange, Horner, HornerTinhDaoHam
from HUST_PPS import ReadxyFromFile, FormatNumber

ImportError: cannot import name 'DaThucNoiSuyLagrangeMocCachDeu' from partially initialized module 'HUST_PPS' (most likely due to a circular import) (c:\Users\Laptop\anaconda3\Lib\site-packages\HUST_PPS\__init__.py)

1. Đọc File
- Dòng đầu chứa x, mỗi số cách nhau bởi dấu cách
- Dòng sau chứa y, mỗi số cách nhau bởi dấu cách

In [27]:
file_path = 'D:/Study/2024.1/PPS/HUST_PPS/files/TimDaThucNoiSuyLagrange.txt' # Thay file_path
x,y = ReadxyFromFile(file_path)
print(x)
print(y)

[1.2 1.4 1.6 1.8 2.  2.2 2.4]
[0.3529 1.4501 2.6476 3.9216 5.2484 6.6055 7.9722]


In [28]:
FormatNumber(4)

In [29]:
LapBangTinhCyLagrange(x,y)

array([[ 1. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2],
       [-0.2,  1. ,  0.2,  0.4,  0.6,  0.8,  1. ],
       [-0.4, -0.2,  1. ,  0.2,  0.4,  0.6,  0.8],
       [-0.6, -0.4, -0.2,  1. ,  0.2,  0.4,  0.6],
       [-0.8, -0.6, -0.4, -0.2,  1. ,  0.2,  0.4],
       [-1. , -0.8, -0.6, -0.4, -0.2,  1. ,  0.2],
       [-1.2, -1. , -0.8, -0.6, -0.4, -0.2,  1. ]])

In [30]:
TinhCyLagrange(x,y)

array([    7.6584,  -188.8151,   861.849 , -1702.0833,  1708.4635,
        -860.0911,   173.0078])

In [31]:
LapBangTichLagrange(x)

array([[   0.    ,    0.    ,    0.    ,    0.    ,    0.    ,    0.    ,
           0.    ,    1.    ],
       [   0.    ,    0.    ,    0.    ,    0.    ,    0.    ,    0.    ,
           1.    ,   -1.2   ],
       [   0.    ,    0.    ,    0.    ,    0.    ,    0.    ,    1.    ,
          -2.6   ,    1.68  ],
       [   0.    ,    0.    ,    0.    ,    0.    ,    1.    ,   -4.2   ,
           5.84  ,   -2.688 ],
       [   0.    ,    0.    ,    0.    ,    1.    ,   -6.    ,   13.4   ,
         -13.2   ,    4.8384],
       [   0.    ,    0.    ,    1.    ,   -8.    ,   25.4   ,  -40.    ,
          31.2384,   -9.6768],
       [   0.    ,    1.    ,  -10.2   ,   43.    ,  -95.88  ,  119.2384,
         -78.4013,   21.289 ],
       [   1.    ,  -12.6   ,   67.48  , -199.08  ,  349.3504, -364.5734,
         209.452 ,  -51.0935]])

In [32]:
LapBangThuongLagrange(x)

array([[   1.    ,  -11.4   ,   53.8   , -134.52  ,  187.9264, -139.0618,
          42.5779,    0.    ],
       [   1.    ,  -11.2   ,   51.8   , -126.56  ,  172.1664, -123.5405,
          36.4954,    0.    ],
       [   1.    ,  -11.    ,   49.88  , -119.272 ,  158.5152, -110.9491,
          31.9334,    0.    ],
       [   1.    ,  -10.8   ,   48.04  , -112.608 ,  146.656 , -100.5926,
          28.3853,    0.    ],
       [   1.    ,  -10.6   ,   46.28  , -106.52  ,  136.3104,  -91.9526,
          25.5468,   -0.    ],
       [   1.    ,  -10.4   ,   44.6   , -100.96  ,  127.2384,  -84.649 ,
          23.2243,    0.    ],
       [   1.    ,  -10.2   ,   43.    ,  -95.88  ,  119.2384,  -78.4013,
          21.289 ,   -0.    ]])

In [33]:
A = DaThucNoiSuyLagrange(x,y)
A

array([-0.0109,  0.1393, -0.6931,  1.2565,  0.9315,  1.0418, -3.2868])

In [38]:
for i in range(0,len(x)):
    t = len(x) - 1
    sum = 0
    for j in range(0,len(A)):
        sum += (A[j]*(x[i]**t))
        t -= 1
    print(sum)

0.3528999993144968
1.4500999992105639
2.647599999091507
3.921599998956559
5.248399998805326
6.605499998637889
7.972199998454883


Tính f(3.95)

In [22]:
Horner(A,3.95)

(array([ 0.0022, -0.0068,  0.0141, -0.1568,  1.1734,  4.4265, 16.5452]),
 np.float64(16.545183128264128))

In [23]:
_ , ans = Horner(A,3.95)
ans

np.float64(16.545183128264128)

Tính f'(3.95)

In [24]:
HornerTinhDaoHam(A,3.95)

([array([ 0.0022, -0.0068,  0.0141, -0.1568,  1.1734,  4.4265, 16.5452]),
  array([ 0.0022,  0.0018,  0.0212, -0.0732,  0.8844,  7.9197]),
  array([0.0022, 0.0104, 0.0621, 0.172 , 1.5636]),
  array([0.0022, 0.0189, 0.1368, 0.7124]),
  array([0.0022, 0.0275, 0.2454]),
  array([0.0022, 0.0361]),
  array([0.0022])],
 [np.float64(16.545183128264128),
  np.float64(7.919744858315024),
  np.float64(3.127222839806257),
  np.float64(4.274121090589295),
  np.float64(5.889973957444478),
  np.float64(4.328124999955436),
  np.float64(1.56250000001819)])

In [25]:
_ , ans = HornerTinhDaoHam(A,3.95)
ans[1]

np.float64(7.919744858315024)