In [1]:
import numpy as np
from HUST_PPS import LapBangTichSterling, TinhCyChanSterling, TinhBangSaiPhanLeSterling, TinhCyLeSterling, DaThucNoiSuyTrungTamSterling
from HUST_PPS import FormatNumber, ReadxyFromFile

In [2]:
file_path = 'D:/Study/2024.1/PPS/HUST_PPS/files/TimDaThucNoiSuyTrungTamSterling.txt' # Thay file_path
x,y = ReadxyFromFile(file_path)
print(x)
print(y)

[5.25  5.375 5.5   5.625 5.75  5.875 6.   ]
[-3.2541 -3.4223 -3.5371 -3.5967 -3.6001 -3.5474 -3.4393]


In [3]:
# FormatNumber(6)

In [4]:
LapBangTichSterling(len(x)) # Theo các số chính phương (VD: 1,4,9,...)

array([[ 0.,  0.,  1.],
       [ 0.,  1., -1.],
       [ 1., -5.,  4.]])

In [5]:
TinhCyChanSterling(x,y,len(x))

array([-3.59670000e+00,  2.81000000e-02, -4.58333333e-05,  1.11111111e-06])

In [6]:
TinhBangSaiPhanLeSterling(x,y,len(x))

array([-0.0315 ,  0.00045,  0.0001 ])

In [7]:
TinhCyLeSterling(x,y,len(x))

array([-3.15000000e-02,  7.50000000e-05,  8.33333333e-07])

In [8]:
DaThucNoiSuyTrungTamSterling(x,y,len(x))

array([ 1.11111111e-06,  8.33333333e-07, -5.13888889e-05,  7.08333333e-05,
        2.81502778e-02, -3.15716667e-02, -3.59670000e+00])