In [1]:
import numpy as np
from HUST_PPS import LapBangTinhCyLagrange, TinhDyLagrangeMocCachDeu, LapBangTichLagrangeMocCachDeu, LapBangThuongLagrangeMocCachDeu, DaThucNoiSuyLagrangeMocCachDeuThamSoT, DaThucNoiSuyLagrangeMocCachDeu, HornerChiaDaThuc
from HUST_PPS import TaoGiaTriXMocCachDeu, FormatNumber

In [2]:
FormatNumber(5)

In [3]:
x = TaoGiaTriXMocCachDeu(1.2,0.2,7)
x

array([1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4])

In [4]:
f_x = x**2 - 3*np.cos(x)
y = np.array(f_x)
y

array([0.35293, 1.4501 , 2.6476 , 3.92161, 5.24844, 6.6055 , 7.97218])

In [5]:
t_ar = (x-1.2)/0.2
t_ar

array([0., 1., 2., 3., 4., 5., 6.])

In [6]:
LapBangTinhCyLagrange(x,y)

array([[ 1. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2],
       [-0.2,  1. ,  0.2,  0.4,  0.6,  0.8,  1. ],
       [-0.4, -0.2,  1. ,  0.2,  0.4,  0.6,  0.8],
       [-0.6, -0.4, -0.2,  1. ,  0.2,  0.4,  0.6],
       [-0.8, -0.6, -0.4, -0.2,  1. ,  0.2,  0.4],
       [-1. , -0.8, -0.6, -0.4, -0.2,  1. ,  0.2],
       [-1.2, -1. , -0.8, -0.6, -0.4, -0.2,  1. ]])

In [7]:
TinhDyLagrangeMocCachDeu(y,6)

array([ 0.00049, -0.01208,  0.05516, -0.10893,  0.10934, -0.05505,
        0.01107])

In [8]:
LapBangTichLagrangeMocCachDeu(6)

array([[    0.,     0.,     0.,     0.,     0.,     0.,     0.,     1.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     1.,    -0.],
       [    0.,     0.,     0.,     0.,     0.,     1.,    -1.,     0.],
       [    0.,     0.,     0.,     0.,     1.,    -3.,     2.,    -0.],
       [    0.,     0.,     0.,     1.,    -6.,    11.,    -6.,     0.],
       [    0.,     0.,     1.,   -10.,    35.,   -50.,    24.,    -0.],
       [    0.,     1.,   -15.,    85.,  -225.,   274.,  -120.,     0.],
       [    1.,   -21.,   175.,  -735.,  1624., -1764.,   720.,    -0.]])

In [9]:
LapBangThuongLagrangeMocCachDeu(6)

array([[    1.,   -21.,   175.,  -735.,  1624., -1764.,   720.,     0.],
       [    1.,   -20.,   155.,  -580.,  1044.,  -720.,     0.,     0.],
       [    1.,   -19.,   137.,  -461.,   702.,  -360.,     0.,     0.],
       [    1.,   -18.,   121.,  -372.,   508.,  -240.,     0.,     0.],
       [    1.,   -17.,   107.,  -307.,   396.,  -180.,     0.,     0.],
       [    1.,   -16.,    95.,  -260.,   324.,  -144.,     0.,     0.],
       [    1.,   -15.,    85.,  -225.,   274.,  -120.,     0.,     0.]])

In [10]:
B = DaThucNoiSuyLagrangeMocCachDeuThamSoT(y,6)
B

array([-0.     ,  0.00001, -0.00008, -0.00372,  0.06173,  1.03923,
        0.35293])

Kiểm tra

In [11]:
for i in range(0,len(t_ar)):
    t = len(t_ar) - 1
    sum = 0
    for j in range(0,len(B)):
        sum += (B[j]*(t_ar[i]**t))
        t -= 1
    print(sum)

0.3529267365699791
1.4500985712992784
2.6475985669038593
3.9216062840792016
5.248440509641188
6.605503351765329
7.97218114662201
