In [13]:
import numpy as np
from HUST_PPS import TinhBangSaiPhan, ChonMoc, TinhCyNewtonMocCachDeu, LapBangTichNewtonMocCachDeu, DaThucNoiSuyNewtonMocCachDeuThamSoT, Horner, HornerTinhDaoHam
from HUST_PPS import TaoGiaTriXMocCachDeu, FormatNumber

f(x) = x^(1/4) + 2sin(x) - 3cos(x)
x = 1, h = 0.118, n = 200
Tính f(15.237), f'(15.237)

In [2]:
FormatNumber(7)

B1: Tính t

In [3]:
num_x = 15.237
h = 0.118
n = 200
somoc = 8
x0 = 1

In [4]:
a1,a2,a3 = ChonMoc(x0,h,n,num_x,somoc)
print(a1)
print(a2)
print(a3)

120.65254237288136
117
124


In [5]:
x_start = x0 + 117*h # x0 + moc_bat_dau*h
x = TaoGiaTriXMocCachDeu(x_start,h,somoc)
x

array([14.806, 14.924, 15.042, 15.16 , 15.278, 15.396, 15.514, 15.632])

In [6]:
f_x = x**(1/4) + 2*np.sin(x) - 3*np.cos(x)
y = np.array(f_x)
y

array([5.3908997, 5.502037 , 5.5639656, 5.5758783, 5.5376633, 5.4499057,
       5.3138791, 5.1315285])

In [7]:
t_ar = (x-x[0])/h
t_ar

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [8]:
TinhBangSaiPhan(x,y)

array([[14.806    ,  5.3908997,  0.       ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ],
       [14.924    ,  5.502037 ,  0.1111374,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ],
       [15.042    ,  5.5639656,  0.0619286, -0.0492088,  0.       ,
         0.       ,  0.       ,  0.       ,  0.       ],
       [15.16     ,  5.5758783,  0.0119127, -0.0500159, -0.0008071,
         0.       ,  0.       ,  0.       ,  0.       ],
       [15.278    ,  5.5376633, -0.038215 , -0.0501277, -0.0001118,
         0.0006953,  0.       ,  0.       ,  0.       ],
       [15.396    ,  5.4499057, -0.0877576, -0.0495427,  0.000585 ,
         0.0006969,  0.0000016,  0.       ,  0.       ],
       [15.514    ,  5.3138791, -0.1360265, -0.0482689,  0.0012738,
         0.0006887, -0.0000081, -0.0000097,  0.       ],
       [15.632    ,  5.1315285, -0.1823507, -0.0463241,  0.0019448,
         0.000671 , -0.0000177, -0.0000096,  0.0000001]])

In [9]:
TinhCyNewtonMocCachDeu(x,y)

array([ 5.3908997,  0.1111374, -0.0246044, -0.0001345,  0.000029 ,
        0.       , -0.       ,  0.       ])

In [10]:
LapBangTichNewtonMocCachDeu(7) # Đa thức Newton tiến t-(n-1), n = 7

array([[    0.,     0.,     0.,     0.,     0.,     0.,     0.,     1.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     1.,    -0.],
       [    0.,     0.,     0.,     0.,     0.,     1.,    -1.,     0.],
       [    0.,     0.,     0.,     0.,     1.,    -3.,     2.,    -0.],
       [    0.,     0.,     0.,     1.,    -6.,    11.,    -6.,     0.],
       [    0.,     0.,     1.,   -10.,    35.,   -50.,    24.,    -0.],
       [    0.,     1.,   -15.,    85.,  -225.,   274.,  -120.,     0.],
       [    1.,   -21.,   175.,  -735.,  1624., -1764.,   720.,    -0.]])

In [11]:
A = DaThucNoiSuyNewtonMocCachDeuThamSoT(x,y)
A

array([ 0.       , -0.       ,  0.0000002,  0.0000277, -0.0003048,
       -0.0238865,  0.1353008,  5.3908997])

In [12]:
for i in range(0,len(t_ar)):
    t = len(t_ar) - 1
    sum = 0
    for j in range(0,len(A)):
        sum += (A[j]*(t_ar[i]**t))
        t -= 1
    print(sum)

5.390899652663925
5.502037024193644
5.563965616570968
5.575878326178309
5.537663340066289
5.449905695518523
5.313879147829198
5.131528459398115


x = x0 + th -> t = (x-x0)/h.
t' = 1 / h

In [59]:
num_x

15.237

In [61]:
x0 = x[0] # Lấy từ mảng x từ việc chọn mốc
t = (num_x-x0)/h
t

np.float64(3.652542372881364)

Tính P(x = 15.237) = P(t = 3.652548)

In [64]:
Horner(A,t)

(array([ 0.       , -0.       ,  0.0000002,  0.0000283, -0.0002015,
        -0.0246224,  0.0453664,  5.5566023]),
 np.float64(5.556602251875762))

In [66]:
HornerTinhDaoHam(A,t)

([array([ 0.       , -0.       ,  0.0000002,  0.0000283, -0.0002015,
         -0.0246224,  0.0453664,  5.5566023]),
  array([ 0.       , -0.       ,  0.0000001,  0.0000287, -0.0000966,
         -0.0249751, -0.0458562]),
  array([ 0.       , -0.       ,  0.0000001,  0.000029 ,  0.0000093,
         -0.0249412]),
  array([ 0.       , -0.       ,  0.       ,  0.000029 ,  0.0001153]),
  array([ 0.       , -0.       , -0.       ,  0.0000289]),
  array([ 0.       , -0.       , -0.0000001]),
  array([ 0., -0.]),
  array([0.])],
 [np.float64(5.556602251875762),
  np.float64(-0.045856229726877695),
  np.float64(-0.04988245407051878),
  np.float64(0.0006920630244074812),
  np.float64(0.0006942382606130033),
  np.float64(-9.624251545148688e-06),
  np.float64(-9.617981617563502e-06),
  np.float64(1.1310464298475154e-07)])

P'(x) = P'(t) t'(x)

Tính P'(x = 15.237) = (1/h)*P'(t = 3.652548)

In [67]:
_ , der = HornerTinhDaoHam(A,t)
print((1/h)*der[1])

-0.388612116329472


Tính P''(x = 15.237)

P''(x) = (P'(t)t'(x))' = P''(t)t'(x) + P'(t)t''(x) = P''(t)t'(x) = (1/h)P''(t)

In [68]:
print((1/h)*der[2])

-0.42273266161456596
